---
title: "Exercises"
output: html_document
---

- Exercise 01:
    - html: [Exercise 01](./Exercises/Exercise_01.html)
    - Rmd: [Exercise 01](./Exercises/Exercise_01.Rmd)
    - [Link to data](https://github.com/rsbrennan/EvolutionaryGenomics/tree/master/Exercises/data)

- Exercise 02:
    - html: [Exercise 02](./Exercises/Exercise_02.html)
    - Rmd: [Exercise 02](./Exercises/Exercise_02.Rmd)

- Exercise 03:
    - html: [Exercise 03](./Exercises/Exercise_03.html)
    - Rmd: [Exercise 03](./Exercises/Exercise_03.Rmd)
    - Solution [Solution](./Exercises/Exercise_03_Solution.html)
    - link to data:  
        - [Structure input file: .stru](https://github.com/rsbrennan/EvolutionaryGenomics/tree/master/Exercises/data/fheteroclitus_coastal.pops.stru)
        - [Structure output files:](https://drive.google.com/drive/folders/1C9KbEUiBFSf_zJ9Cor8piH5TN8Buh2X-?usp=sharing)
        
- Exercise 04:
    - html: [Exercise 04](./Exercises/Exercise_04.html)
    - Rmd: [Exercise 04](./Exercises/Exercise_04.Rmd)
    - link to data:  
        - [budbug data](https://github.com/rsbrennan/EvolutionaryGenomics/blob/master/Exercises/data/bedbugs_cross_data.csv)
        
- Exercise 05:
    - html: [Exercise 05](./Exercises/Exercise_05.html)
    - Rmd: [Exercise 05](./Exercises/Exercise_05.Rmd)

- Exercise 06:
    - html: [Exercise 06](./Exercises/Exercise_06.html)
    - Rmd: [Exercise 06](./Exercises/Exercise_06.Rmd)
    - Solution [Solution](./Exercises/Exercise_06_Solution.html)
    - link to data:  
        - [Genotype  file](https://github.com/rsbrennan/EvolutionaryGenomics/tree/master/Exercises/data/BergEtAl2017_AtlanticCod_TransatlanticDataset.raw)
        - [Map file](https://github.com/rsbrennan/EvolutionaryGenomics/tree/master/Exercises/data/BergEtAl2017_AtlanticCod_TransatlanticDataset.map)

- Exercise 07
    - Using the exercise from Raphael Royaute, Ned Dochtermann, and Ann Hedrick: 
        - [Link to exercise](https://github.com/rsbrennan/h2_breeders_equation/blob/master/Evolving%20Crickets%20Lab.pdf)
        

- Exercise 09
    - html: [Exercise 09](./Exercises/Exercise_09.html)
    - Rmd: [Exercise 09](./Exercises/Exercise_09.Rmd)
